version: '3'
services:

  mariadb_master:
    image: mariadb:10.6
    container_name: mariadb_10_6
    restart: always

    ports:
      - "3307:3306"

    volumes:
      - $PWD/mariadb-data:/var/lib/mysql
#      - $PWD/master:/etc/mysql/conf.d

    # command: --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;'

    environment:
      #MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: klai_dev_!@#
      MYSQL_DATABASE: b2c
      MYSQL_USER: b2c_user
      MYSQL_PASSWORD: b2c_password
      TZ: Asia/Seoul

#networks:
#    default:
#      external:
#        name: db_network

# docker-compose up --build -d
# docker-compose down
